### ISSUE TITLE
Notarize Timer for macOS

### ISSUE THREAD

**Issue by connorads** [michaelvillar/timer-app#101] opened 2020-11-10 11:42 UTC
`Timer` is currently not [notarized](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution), which means that it is difficult to run on modern macOS versions [like Catalina due to enhanced security features](https://support.apple.com/en-euro/HT202491).

![image](https://user-images.githubusercontent.com/10026538/98669804-b3bc9f00-2349-11eb-8fa8-4d3311b71fd6.png)

- [Notarizing macOS Software Before Distribution](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution)
- [Apple Developer Program Membership Fee Waivers](https://developer.apple.com/support/membership-fee-waiver/)

**Comment by karbassi** [comment] 2020-11-11 20:19
[Safely open apps on your Mac](https://support.apple.com/en-us/HT202491)

Duplicate of #97

**Closed as completed by karbassi** 2020-11-11 20:19 UTC
