### ISSUE TITLE
“Timer” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by jreyes085** [michaelvillar/timer-app#134] opened 2024-04-24 10:35 UTC
**Describe the bug**
Due to policy on my laptop I cannot execute the app as I receive error below:
“Timer” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
Homebrew Cask downloaded this file yesterday at 09:35.

**To Reproduce**
1. brew install --cask michaelvillar-timer
2. Attempt to open the app:
- Clicking on app (UI)
- OR: sudo /Applications/Timer.app/Contents/MacOS/Timer 
4. See error in description.

**Expected behavior**
It should let me execute the app. Please add yourself to appstore or something so that you can be verified as a developer.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS version: MacOS Sonoma 14.3

**Additional context**
N/A

**Comment by karbassi** [comment] 2024-04-24 18:31
[Safely open apps on your Mac](https://support.apple.com/en-us/HT202491)

Duplicate of #97

**Closed as completed by karbassi** 2024-04-24 18:31 UTC
