### ISSUE TITLE
Cannot open app. System moved to Bin

### ISSUE THREAD

**Issue by zzj0402** [michaelvillar/timer-app#120] opened 2021-09-01 01:13 UTC
**Describe the bug**
Cannot open app.

**To Reproduce**
Click on Timer app

**Expected behavior**
Open the file

**Screenshots**
![image](https://user-images.githubusercontent.com/15345547/131595556-c3e7b773-8354-48a5-bb5c-472b7639454a.png)

 - OS version: macOS 11.5.1
 - Timer version 1.6.0

**Comment by karbassi** [comment] 2021-09-01 02:56
[Safely open apps on your Mac](https://support.apple.com/en-us/HT202491)

Duplicate of #97

**Closed as completed by karbassi** 2021-09-01 02:56 UTC
