### ISSUE TITLE
the triangle, is something wrong?

### ISSUE THREAD

**Issue by naoyeye** [michaelvillar/timer-app#56] opened 2019-05-30 04:04 UTC
the translucent circles do not cover the triangles.

![tiN4JBProf](https://user-images.githubusercontent.com/434428/58607409-2232ac00-82d2-11e9-9ced-c48d8fd7f76c.gif)

**Comment by karbassi** [comment] 2019-05-30 19:09
Duplicate of #40

**Closed as completed by karbassi** 2019-05-30 19:09 UTC
